apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: cceaddon-log-agent
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-08-01T08:45:39Z"
  generation: 1
  labels:
    app: log-agent-log-operator
    app.kubernetes.io/managed-by: Helm
    chart: log-agent-1.7.3
    heritage: Helm
    release: cceaddon-log-agent
  name: log-agent-log-operator
  namespace: monitoring
  resourceVersion: "23861"
  uid: a04c5f16-c9dc-45db-9d6c-795aaa4fc873
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: log-agent-log-operator
      release: cceaddon-log-agent
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8443"
        prometheus.io/scheme: https
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: log-agent-log-operator
        release: cceaddon-log-agent
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - log-agent-log-operator
              topologyKey: topology.kubernetes.io/zone
            weight: 100
      containers:
      - command:
        - /var/paas/log-operator/log-operator
        - --enable-leader-election
        - --log-print-type=console
        - --enable-fluent-bit-use-kubelet=true
        - --lts-compress-type=gzip
        - --enable-webhook=true
        - --lts-enterprise-project-id=0
        - --buffer-chunk-size=128k
        - --buffer-max-size=512k
        - --mem-buf-limit=40MB
        - --aom-endpoint=https://aom.tr-west-1.myhuaweicloud.com
        - --lts-endpoint=https://lts.tr-west-1.myhuaweicloud.com
        - --lts-access-endpoint=https://100.125.8.20:8102
        - --init-lts-for-stdout=true
        - --init-lts-for-event=true
        - --enable-ssl=true
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: INSECURE_SKIP_VERIFY
          value: "true"
        - name: Region
          value: tr-west-1
        - name: projectID
          value: b19971231bdf44d4b926977511fd59e1
        - name: clusterID
          value: 6203370f-6eb3-11f0-81dd-0255ac10003e
        - name: clusterName
          value: kubemigrate
        - name: PAAS_CRYPTO_PATH
          value: /etc/cipher
        - name: APP_NAME
          value: CCE
        image: swr.tr-west-1.myhuaweicloud.com/hwofficial/log-operator:1.7.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - test `ps -eo stat,command | grep -v grep | grep log-operator | awk '{print
              $1}' | egrep "^Z|^T" | wc -l` == 0
          failureThreshold: 3
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        name: log-operator
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 10000
          runAsUser: 10000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /var/paas/sys/log
          name: varpaassyslog
        - mountPath: /etc/cipher/root.key
          name: rootkey
          readOnly: true
        - mountPath: /etc/cipher/common_shared.key
          name: commonsharedkey
          readOnly: true
        - mountPath: /var/paas/cert
          name: cert
          readOnly: true
        - mountPath: /var/paas/fluent-bit-config
          name: fluent-bit-config-service
          readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      initContainers:
      - command:
        - /var/paas/log-adaptor/log-adaptor
        - --absolute-crd-dir-path=/var/paas/log-adaptor/crds/
        - --retry-times=3
        - --force-upgrade=false
        - --log-print-type=console
        - --cop-logs-operator-name=log-agent-log-operator
        env:
        - name: APP_NAME
          value: CCE
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PAAS_CRYPTO_PATH
          value: /etc/cipher
        image: swr.tr-west-1.myhuaweicloud.com/hwofficial/log-adaptor:1.7.3
        imagePullPolicy: IfNotPresent
        name: init-log-operator
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /var/paas/sys/log
          name: varpaassyslog
        - mountPath: /etc/cipher/root.key
          name: rootkey
          readOnly: true
        - mountPath: /etc/cipher/common_shared.key
          name: commonsharedkey
          readOnly: true
      - command:
        - /bin/sh
        - -c
        - mkdir -p /var/paas/sys/log/log-operator && chmod 750 /var/paas/sys/log/log-operator
          && chown -R 10000:10000 /var/paas/sys/log
        image: swr.tr-west-1.myhuaweicloud.com/hwofficial/log-operator:1.7.3
        imagePullPolicy: IfNotPresent
        name: init
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/paas/sys/log
          name: varpaassyslog
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10000
      serviceAccount: log-agent-log-operator
      serviceAccountName: log-agent-log-operator
      terminationGracePeriodSeconds: 5
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 30
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 30
      - key: role
        operator: Exists
      - effect: NoSchedule
        key: distribution.io/category
        operator: Equal
        value: IES
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: localtime
      - hostPath:
          path: /var/paas/sys/log
          type: ""
        name: varpaassyslog
      - hostPath:
          path: /var/paas/srv/kubernetes/root.key
          type: ""
        name: rootkey
      - hostPath:
          path: /var/paas/srv/kubernetes/common_shared.key
          type: ""
        name: commonsharedkey
      - name: cert
        secret:
          defaultMode: 416
          items:
          - key: caCert
            path: caCert
          - key: serverCert
            path: serverCert
          - key: serverKey
            path: serverKey
          optional: true
          secretName: log-agent-cert-secret
      - configMap:
          defaultMode: 416
          name: log-agent-fluent-bit-config-service
        name: fluent-bit-config-service
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-08-01T10:27:33Z"
    lastUpdateTime: "2025-08-01T10:27:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-01T10:27:33Z"
    lastUpdateTime: "2025-08-01T10:27:37Z"
    message: ReplicaSet "log-agent-log-operator-85d57c94f7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
