apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: cceaddon-cie-collector
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-08-01T08:45:47Z"
  labels:
    app: node-exporter
    app.kubernetes.io/managed-by: Helm
    release: cceaddon-cie-collector
  name: node-exporter
  namespace: monitoring
  resourceVersion: "857"
  uid: 5abae0cf-491b-4b88-97b0-551cd052791c
spec:
  clusterIP: 10.247.139.114
  clusterIPs:
  - 10.247.139.114
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: node-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
