apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-08-01T10:27:23Z"
  labels:
    operated-prometheus: "true"
  name: prometheus-operated
  namespace: monitoring
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    kind: Prometheus
    name: server
    uid: 621f6634-3432-4432-9c45-9df7e4dc9f65
  resourceVersion: "23634"
  uid: bf3965c8-5672-4b04-b5da-93d4fcdd4d1b
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
