apiVersion: v1
kind: Pod
metadata:
  annotations:
    localdns.cce.io/servers: '["169.254.20.10"]'
    node-local-dns-webhook.k8s.io/status: injected
  creationTimestamp: "2025-08-01T10:34:12Z"
  generateName: checkoutservice-b97f7b4c5-
  labels:
    app: checkoutservice
    pod-template-hash: b97f7b4c5
  name: checkoutservice-b97f7b4c5-88fxb
  namespace: demo-app
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: checkoutservice-b97f7b4c5
    uid: 5cd72dc7-ead6-4cfd-bd76-ef0d6fbcc52e
  resourceVersion: "26751"
  uid: d13f6fff-76df-488f-8efb-12323f2e5fef
spec:
  containers:
  - env:
    - name: PORT
      value: "5050"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: productcatalogservice:3550
    - name: SHIPPING_SERVICE_ADDR
      value: shippingservice:50051
    - name: PAYMENT_SERVICE_ADDR
      value: paymentservice:50051
    - name: EMAIL_SERVICE_ADDR
      value: emailservice:5000
    - name: CURRENCY_SERVICE_ADDR
      value: currencyservice:7000
    - name: CART_SERVICE_ADDR
      value: cartservice:7070
    image: swr.tr-west-1.myhuaweicloud.com/cce-training/checkoutservice:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      grpc:
        port: 5050
        service: ""
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: server
    ports:
    - containerPort: 5050
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      grpc:
        port: 5050
        service: ""
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-clnbm
      readOnly: true
  dnsConfig:
    nameservers:
    - 169.254.20.10
    - 10.247.3.10
    options:
    - name: single-request-reopen
      value: ""
    - name: timeout
      value: "2"
    - name: ndots
      value: "5"
    searches:
    - demo-app.svc.cluster.local
    - svc.cluster.local
    - cluster.local
  dnsPolicy: None
  enableServiceLinks: true
  nodeName: 192.168.0.121
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-clnbm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:16Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:12Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:16Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:16Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:12Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://4af5fb76d63d8d40408fade9ba643e94a9a782e459c9b65c024e043d5c84f003
    image: swr.tr-west-1.myhuaweicloud.com/cce-training/checkoutservice:latest
    imageID: swr.tr-west-1.myhuaweicloud.com/cce-training/checkoutservice@sha256:ebd6a04daa3b967390af764ee4a66e4071c319628fba45ace6b51ea0360817fb
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-01T10:34:15Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-clnbm
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.0.121
  hostIPs:
  - ip: 192.168.0.121
  phase: Running
  podIP: 10.0.0.4
  podIPs:
  - ip: 10.0.0.4
  qosClass: Burstable
  startTime: "2025-08-01T10:34:12Z"
