apiVersion: v1
kind: Pod
metadata:
  annotations:
    localdns.cce.io/servers: '["169.254.20.10"]'
    node-local-dns-webhook.k8s.io/status: injected
  creationTimestamp: "2025-08-01T10:34:12Z"
  generateName: currencyservice-66dbbf9f89-
  labels:
    app: currencyservice
    pod-template-hash: 66dbbf9f89
  name: currencyservice-66dbbf9f89-kl42k
  namespace: demo-app
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: currencyservice-66dbbf9f89
    uid: 27d6a887-7b07-4986-af32-1725815af240
  resourceVersion: "26909"
  uid: 72070ba7-329d-4d94-bd4f-e2bfad73d083
spec:
  containers:
  - env:
    - name: PORT
      value: "7000"
    - name: DISABLE_PROFILER
      value: "1"
    image: swr.tr-west-1.myhuaweicloud.com/cce-training/currencyservice:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      grpc:
        port: 7000
        service: ""
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: server
    ports:
    - containerPort: 7000
      name: grpc
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      grpc:
        port: 7000
        service: ""
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cskkm
      readOnly: true
  dnsConfig:
    nameservers:
    - 169.254.20.10
    - 10.247.3.10
    options:
    - name: single-request-reopen
      value: ""
    - name: timeout
      value: "2"
    - name: ndots
      value: "5"
    searches:
    - demo-app.svc.cluster.local
    - svc.cluster.local
    - cluster.local
  dnsPolicy: None
  enableServiceLinks: true
  nodeName: 192.168.0.121
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 5
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-cskkm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:24Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:12Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:33Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:33Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:12Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://66e8c3aaa001daeb8c322d7943b0343d746ce5e9c23a5f86dec9137ff9384b76
    image: swr.tr-west-1.myhuaweicloud.com/cce-training/currencyservice:latest
    imageID: swr.tr-west-1.myhuaweicloud.com/cce-training/currencyservice@sha256:062ae02441062107410023da297da5b70d625c44082e34e4ac27c40c94a014df
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-01T10:34:23Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-cskkm
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.0.121
  hostIPs:
  - ip: 192.168.0.121
  phase: Running
  podIP: 10.0.0.5
  podIPs:
  - ip: 10.0.0.5
  qosClass: Burstable
  startTime: "2025-08-01T10:34:12Z"
