apiVersion: v1
kind: Pod
metadata:
  annotations:
    localdns.cce.io/servers: '["169.254.20.10"]'
    node-local-dns-webhook.k8s.io/status: injected
  creationTimestamp: "2025-08-01T10:34:13Z"
  generateName: recommendationservice-fc699875f-
  labels:
    app: recommendationservice
    pod-template-hash: fc699875f
  name: recommendationservice-fc699875f-2jwth
  namespace: demo-app
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: recommendationservice-fc699875f
    uid: bc5d5492-f12c-4997-8f8e-808f76548c35
  resourceVersion: "26800"
  uid: 59c087ef-447c-4a0c-9eb2-1da8fd625efe
spec:
  containers:
  - env:
    - name: PORT
      value: "8080"
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: productcatalogservice:3550
    - name: DISABLE_PROFILER
      value: "1"
    image: swr.tr-west-1.myhuaweicloud.com/cce-training/recommendationservice:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      grpc:
        port: 8080
        service: ""
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: server
    ports:
    - containerPort: 8080
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      grpc:
        port: 8080
        service: ""
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 200m
        memory: 450Mi
      requests:
        cpu: 100m
        memory: 220Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ksbvr
      readOnly: true
  dnsConfig:
    nameservers:
    - 169.254.20.10
    - 10.247.3.10
    options:
    - name: single-request-reopen
      value: ""
    - name: timeout
      value: "2"
    - name: ndots
      value: "5"
    searches:
    - demo-app.svc.cluster.local
    - svc.cluster.local
    - cluster.local
  dnsPolicy: None
  enableServiceLinks: true
  nodeName: 192.168.0.35
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 5
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-ksbvr
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:17Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f9d2d3973b1ea5afe766231be2adc60c6eaadc4bdb092dca66eab26f9ab2303c
    image: swr.tr-west-1.myhuaweicloud.com/cce-training/recommendationservice:latest
    imageID: swr.tr-west-1.myhuaweicloud.com/cce-training/recommendationservice@sha256:6914bf858821f7f088ca7c76f9c484e0fe3eaafa1c099793a53fb813361a2572
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-01T10:34:16Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-ksbvr
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.0.35
  hostIPs:
  - ip: 192.168.0.35
  phase: Running
  podIP: 10.0.1.133
  podIPs:
  - ip: 10.0.1.133
  qosClass: Burstable
  startTime: "2025-08-01T10:34:13Z"
