apiVersion: v1
kind: Pod
metadata:
  annotations:
    localdns.cce.io/servers: '["169.254.20.10"]'
    node-local-dns-webhook.k8s.io/status: injected
  creationTimestamp: "2025-08-01T10:34:13Z"
  generateName: productcatalogservice-7c96c45845-
  labels:
    app: productcatalogservice
    pod-template-hash: 7c96c45845
  name: productcatalogservice-7c96c45845-m56d2
  namespace: demo-app
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: productcatalogservice-7c96c45845
    uid: 481a93ff-a8d5-4ff7-8edd-6b2d06f71221
  resourceVersion: "26726"
  uid: 19e86249-8ec6-4f04-9e40-6d6c39fa0ed4
spec:
  containers:
  - env:
    - name: PORT
      value: "3550"
    - name: DISABLE_PROFILER
      value: "1"
    image: swr.tr-west-1.myhuaweicloud.com/cce-training/productcatalogservice:latest
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      grpc:
        port: 3550
        service: ""
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: server
    ports:
    - containerPort: 3550
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      grpc:
        port: 3550
        service: ""
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2l5rt
      readOnly: true
  dnsConfig:
    nameservers:
    - 169.254.20.10
    - 10.247.3.10
    options:
    - name: single-request-reopen
      value: ""
    - name: timeout
      value: "2"
    - name: ndots
      value: "5"
    searches:
    - demo-app.svc.cluster.local
    - svc.cluster.local
    - cluster.local
  dnsPolicy: None
  enableServiceLinks: true
  nodeName: 192.168.0.35
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 5
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2l5rt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:15Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:34:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://2be7de0364d98fb6392a6a267f62059fe1390bd86aa072ba7346d7a5b5aa981a
    image: swr.tr-west-1.myhuaweicloud.com/cce-training/productcatalogservice:latest
    imageID: swr.tr-west-1.myhuaweicloud.com/cce-training/productcatalogservice@sha256:2510d97f1956269fcde7021845e389c32491a121b77df7cffd73f702aabc80e4
    lastState: {}
    name: server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-01T10:34:14Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2l5rt
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.0.35
  hostIPs:
  - ip: 192.168.0.35
  phase: Running
  podIP: 10.0.1.132
  podIPs:
  - ip: 10.0.1.132
  qosClass: Burstable
  startTime: "2025-08-01T10:34:13Z"
