apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"recommendationservice"},"name":"recommendationservice","namespace":"demo-app"},"spec":{"ports":[{"name":"grpc","port":8080,"targetPort":8080}],"selector":{"app":"recommendationservice"},"type":"ClusterIP"}}
  creationTimestamp: "2025-08-01T10:34:13Z"
  labels:
    app: recommendationservice
  name: recommendationservice
  namespace: demo-app
  resourceVersion: "26655"
  uid: 8bcb3f83-82e5-46eb-b385-d7f0c3d92576
spec:
  clusterIP: 10.247.129.111
  clusterIPs:
  - 10.247.129.111
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: recommendationservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
