apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"paymentservice"},"name":"paymentservice","namespace":"demo-app"},"spec":{"ports":[{"name":"grpc","port":50051,"targetPort":50051}],"selector":{"app":"paymentservice"},"type":"ClusterIP"}}
  creationTimestamp: "2025-08-01T10:34:13Z"
  labels:
    app: paymentservice
  name: paymentservice
  namespace: demo-app
  resourceVersion: "26636"
  uid: 4080ca98-0434-489f-baf3-62856d5b2474
spec:
  clusterIP: 10.247.40.159
  clusterIPs:
  - 10.247.40.159
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: paymentservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
