apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: cceaddon-nginx-ingress
    meta.helm.sh/release-namespace: demo-app
  creationTimestamp: "2025-08-01T10:36:36Z"
  labels:
    app: nginx-ingress
    app.kubernetes.io/managed-by: Helm
    chart: nginx-ingress-3.0.34
    component: controller
    heritage: Helm
    release: cceaddon-nginx-ingress
  name: cceaddon-nginx-ingress-controller-metrics
  namespace: demo-app
  resourceVersion: "27763"
  uid: c1ec2f67-d8a6-4563-8b44-eabe4e1a4464
spec:
  clusterIP: 10.247.10.56
  clusterIPs:
  - 10.247.10.56
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9913
    protocol: TCP
    targetPort: metrics
  selector:
    app: nginx-ingress
    component: controller
    release: cceaddon-nginx-ingress
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
