apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: cceaddon-nginx-ingress
    meta.helm.sh/release-namespace: demo-app
  creationTimestamp: "2025-08-01T10:36:36Z"
  labels:
    app: nginx-ingress
    app.kubernetes.io/managed-by: Helm
    chart: nginx-ingress-3.0.34
    component: default-backend
    heritage: Helm
    release: cceaddon-nginx-ingress
  name: cceaddon-nginx-ingress-default-backend
  namespace: demo-app
  resourceVersion: "27759"
  uid: b6040e54-90ea-4c22-a6ee-c865e524b610
spec:
  clusterIP: 10.247.13.42
  clusterIPs:
  - 10.247.13.42
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx-ingress
    component: default-backend
    release: cceaddon-nginx-ingress
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
