apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"cartservice"},"name":"cartservice","namespace":"demo-app"},"spec":{"ports":[{"name":"grpc","port":7070,"targetPort":7070}],"selector":{"app":"cartservice"},"type":"ClusterIP"}}
  creationTimestamp: "2025-08-01T10:34:12Z"
  labels:
    app: cartservice
  name: cartservice
  namespace: demo-app
  resourceVersion: "26570"
  uid: 1c4c13b4-6d1b-4c88-913a-14b9dd4f1a1d
spec:
  clusterIP: 10.247.225.231
  clusterIPs:
  - 10.247.225.231
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: cartservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
