apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"productcatalogservice"},"name":"productcatalogservice","namespace":"demo-app"},"spec":{"ports":[{"name":"grpc","port":3550,"targetPort":3550}],"selector":{"app":"productcatalogservice"},"type":"ClusterIP"}}
  creationTimestamp: "2025-08-01T10:34:13Z"
  labels:
    app: productcatalogservice
  name: productcatalogservice
  namespace: demo-app
  resourceVersion: "26639"
  uid: d76c60dd-116e-46ac-a3b8-eb8b98ede2a1
spec:
  clusterIP: 10.247.65.64
  clusterIPs:
  - 10.247.65.64
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 3550
    protocol: TCP
    targetPort: 3550
  selector:
    app: productcatalogservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
