apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"frontend"},"name":"frontend","namespace":"demo-app"},"spec":{"ports":[{"name":"http","port":80,"targetPort":8080}],"selector":{"app":"frontend"},"type":"ClusterIP"}}
  creationTimestamp: "2025-08-01T10:34:12Z"
  labels:
    app: frontend
  name: frontend
  namespace: demo-app
  resourceVersion: "26629"
  uid: 10cc3e5a-6d4a-4cf6-bef5-2adf067e1189
spec:
  clusterIP: 10.247.75.49
  clusterIPs:
  - 10.247.75.49
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
