apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"emailservice"},"name":"emailservice","namespace":"demo-app"},"spec":{"ports":[{"name":"grpc","port":5000,"targetPort":8080}],"selector":{"app":"emailservice"},"type":"ClusterIP"}}
  creationTimestamp: "2025-08-01T10:34:12Z"
  labels:
    app: emailservice
  name: emailservice
  namespace: demo-app
  resourceVersion: "26616"
  uid: 23868c01-f160-4822-8b92-cc96385e3379
spec:
  clusterIP: 10.247.62.54
  clusterIPs:
  - 10.247.62.54
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 5000
    protocol: TCP
    targetPort: 8080
  selector:
    app: emailservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
