apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: cceaddon-npd
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2025-08-01T08:45:38Z"
  generation: 1
  labels:
    app: node-problem-controller
    app.kubernetes.io/managed-by: Helm
    release: cceaddon-npd
  name: node-problem-controller
  namespace: kube-system
  resourceVersion: "23905"
  uid: fa6b8c84-0c2e-4e82-8f3d-dfd26bb88b1d
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-problem-controller-cce
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 82b999bfff05a83dd3dae4693921fbdf9bff3608ff68a2368f5029426ed0f681
      creationTimestamp: null
      labels:
        app: node-problem-controller-cce
        release: cceaddon-npd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - node-problem-controller-cce
              topologyKey: topology.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - node-problem-controller-cce
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - /bin/sh
        - -c
        - /var/paas/node-problem-controller/node-problem-controller --metrics-addr=$(POD_IP):9090
          --healthz-addr=$(POD_IP):8080
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: swr.tr-west-1.myhuaweicloud.com/hwofficial/node-problem-controller:1.19.20
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "5"
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: npc
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 30m
            memory: 100Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-volume
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
      dnsPolicy: ClusterFirst
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10000
        seccompProfile:
          type: Unconfined
      serviceAccount: cceaddon-npc
      serviceAccountName: cceaddon-npc
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node-problem-controller.cce.io
        operator: Exists
        tolerationSeconds: 60
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 60
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 60
      volumes:
      - configMap:
          defaultMode: 416
          name: cceaddon-npc-config
        name: config-volume
      - hostPath:
          path: /etc/localtime
          type: File
        name: localtime
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2025-08-01T10:27:32Z"
    lastUpdateTime: "2025-08-01T10:27:32Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-08-01T10:27:32Z"
    lastUpdateTime: "2025-08-01T10:27:42Z"
    message: ReplicaSet "node-problem-controller-7c699f7f98" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
