apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-08-01T10:26:53Z"
  generateName: icagent-
  labels:
    app: icagent
    controller-revision-hash: 6c6c68584d
    pod-template-generation: "1"
  name: icagent-trhvz
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: icagent
    uid: 1d312451-cf17-4017-b31e-32c4679af98a
  resourceVersion: "23385"
  uid: d82e9942-d7b5-46e6-8dd6-07770be5d484
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - 192.168.0.121
  containers:
  - command:
    - /bin/sh
    - /opt/ICAgentPkg/install.sh
    env:
    - name: sysimage_root
      value: /host
    - name: SYSTEMD_IGNORE_CHROOT
      value: "yes"
    - name: elbIP
      value: 100.125.8.20
    - name: cluster_id
      value: 6203370f-6eb3-11f0-81dd-0255ac10003e
    - name: cluster_name
      value: kubemigrate
    - name: CustomHostTag
      value: k8s-log-6203370f-6eb3-11f0-81dd-0255ac10003e
    - name: TSOEnable
      value: "false"
    - name: log_switch
      value: "false"
    - name: accessDomain
    - name: IC_VERIFYCN_ENABLE
      value: "false"
    - name: AMS_PODLB_DOMAIN
    - name: ALS_PODLB_DOMAIN
    - name: AOM_VPCEP_URL
      value: aom-access.tr-west-1.myhuaweicloud.com
    - name: LTS_VPCEP_URL
      value: lts-access.tr-west-1.myhuaweicloud.com
    image: swr.tr-west-1.myhuaweicloud.com/op_svc_apm/icagent:7.3.6
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - /opt/oss/servicemgr/ICAgent/bin/manual/uninstall.sh
    livenessProbe:
      failureThreshold: 3
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 28002
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: icagent
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/
      name: dockersock
    - mountPath: /run/
      name: run
    - mountPath: /etc/passwd
      name: etcpwd
    - mountPath: /etc/group
      name: etcgroup
    - mountPath: /etc/localtime
      name: localtime
    - mountPath: /var/etc/profile
      name: profile
    - mountPath: /var/paas/srv/kubernetes/
      name: k8s-cert
    - mountPath: /tmp/apm/caf/
      name: agentid-home
    - mountPath: /var/lib/docker/
      name: docker-home
    - mountPath: /var/lib/kubelet/pods/
      mountPropagation: HostToContainer
      name: pods-home
    - mountPath: /var/log/containers/
      name: docker-log
    - mountPath: /var/log/pods/
      name: docker-pods-log
    - mountPath: /paas-apm/collectors/pinpoint/
      name: pinpoint-vm
    - mountPath: /var/paas/sys/log/
      name: cff-logdir
    - mountPath: /opt/apm-container
      name: pinpoint-apm-container
    - mountPath: /var/share/oss/manager/ICProbeAgent/
      name: icagent-configdir
    - mountPath: /var/ICAgent/
      name: icagent-log
    - mountPath: /opt/oss/servicemgr/ICAgent/
      name: icagent-workdir
    - mountPath: /host/
      mountPropagation: HostToContainer
      name: sysimage
    - mountPath: /mnt/paas/runtime/
      name: runtime-home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-z7j4z
      readOnly: true
  dnsConfig:
    options:
    - name: single-request-reopen
      value: ""
    - name: timeout
      value: "2"
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostIPC: true
  hostNetwork: true
  hostPID: true
  nodeName: 192.168.0.121
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: icagent-account
  serviceAccountName: icagent-account
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /var/run/
      type: ""
    name: dockersock
  - hostPath:
      path: /run/
      type: ""
    name: run
  - hostPath:
      path: /etc/passwd
      type: ""
    name: etcpwd
  - hostPath:
      path: /etc/group
      type: ""
    name: etcgroup
  - hostPath:
      path: /etc/localtime
      type: ""
    name: localtime
  - hostPath:
      path: /etc/profile
      type: ""
    name: profile
  - hostPath:
      path: /var/paas/srv/kubernetes/
      type: ""
    name: k8s-cert
  - hostPath:
      path: /var/lib/docker/
      type: ""
    name: docker-home
  - hostPath:
      path: /var/lib/kubelet/pods/
      type: ""
    name: pods-home
  - hostPath:
      path: /var/log/containers/
      type: ""
    name: docker-log
  - hostPath:
      path: /var/log/pods/
      type: ""
    name: docker-pods-log
  - hostPath:
      path: /var/paas-apm/collectors/pinpoint/
      type: ""
    name: pinpoint-vm
  - hostPath:
      path: /var/opt/apm-container/
      type: ""
    name: pinpoint-apm-container
  - hostPath:
      path: /tmp/apm/caf/
      type: ""
    name: agentid-home
  - hostPath:
      path: /var/ICAgent/
      type: ""
    name: icagent-log
  - hostPath:
      path: /var/share/oss/manager/ICProbeAgent/
      type: ""
    name: icagent-configdir
  - hostPath:
      path: /var/opt/oss/servicemgr/ICAgent/
      type: ""
    name: icagent-workdir
  - hostPath:
      path: /var/paas/sys/log/
      type: ""
    name: cff-logdir
  - hostPath:
      path: /
      type: ""
    name: sysimage
  - hostPath:
      path: /mnt/paas/runtime/
      type: ""
    name: runtime-home
  - name: kube-api-access-z7j4z
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:11Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:26:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:11Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:11Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:26:53Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://d450c7ab35be089ef2deed76276186499db271dbb1e33b1acba316a5ed8a190e
    image: swr.tr-west-1.myhuaweicloud.com/op_svc_apm/icagent:7.3.6
    imageID: swr.tr-west-1.myhuaweicloud.com/op_svc_apm/icagent@sha256:ff7745a0b3b94ab70389a7f8af21a5c711ef1f933ac0373caf07e0538e7e3387
    lastState: {}
    name: icagent
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-01T10:27:11Z"
    volumeMounts:
    - mountPath: /var/run/
      name: dockersock
    - mountPath: /run/
      name: run
    - mountPath: /etc/passwd
      name: etcpwd
    - mountPath: /etc/group
      name: etcgroup
    - mountPath: /etc/localtime
      name: localtime
    - mountPath: /var/etc/profile
      name: profile
    - mountPath: /var/paas/srv/kubernetes/
      name: k8s-cert
    - mountPath: /tmp/apm/caf/
      name: agentid-home
    - mountPath: /var/lib/docker/
      name: docker-home
    - mountPath: /var/lib/kubelet/pods/
      name: pods-home
    - mountPath: /var/log/containers/
      name: docker-log
    - mountPath: /var/log/pods/
      name: docker-pods-log
    - mountPath: /paas-apm/collectors/pinpoint/
      name: pinpoint-vm
    - mountPath: /var/paas/sys/log/
      name: cff-logdir
    - mountPath: /opt/apm-container
      name: pinpoint-apm-container
    - mountPath: /var/share/oss/manager/ICProbeAgent/
      name: icagent-configdir
    - mountPath: /var/ICAgent/
      name: icagent-log
    - mountPath: /opt/oss/servicemgr/ICAgent/
      name: icagent-workdir
    - mountPath: /host/
      name: sysimage
    - mountPath: /mnt/paas/runtime/
      name: runtime-home
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-z7j4z
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.0.121
  hostIPs:
  - ip: 192.168.0.121
  phase: Running
  podIP: 192.168.0.121
  podIPs:
  - ip: 192.168.0.121
  qosClass: Burstable
  startTime: "2025-08-01T10:26:53Z"
