apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: "9253"
    prometheus.io/scrape: "true"
  creationTimestamp: "2025-08-01T10:27:02Z"
  generateName: node-local-dns-
  labels:
    controller-revision-hash: fb77545c4
    k8s-app: node-local-dns
    pod-template-generation: "1"
    release: cceaddon-node-local-dns
  name: node-local-dns-7zprd
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: node-local-dns
    uid: ca0a733d-b739-4aba-a261-7872c513637f
  resourceVersion: "23643"
  uid: 870e5a86-b20e-4439-9e25-7bddd730bad2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - 192.168.0.73
  containers:
  - args:
    - -localip
    - 169.254.20.10
    - -upstreamsvc
    - coredns
    - -skipteardown=true
    - -conf
    - /etc/corefile-path/Corefile
    image: swr.tr-west-1.myhuaweicloud.com/hwofficial/k8s-dns-node-cache:1.23.1
    imagePullPolicy: Always
    lifecycle:
      preStop:
        exec:
          command:
          - sleep
          - "30"
    livenessProbe:
      failureThreshold: 3
      httpGet:
        host: 169.254.20.10
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: node-cache
    ports:
    - containerPort: 9253
      hostPort: 9253
      name: metrics
      protocol: TCP
    - containerPort: 53
      hostPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      hostPort: 53
      name: dns-tcp
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        host: 169.254.20.10
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 25m
        memory: 5Mi
    securityContext:
      privileged: true
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/corefile-path
      name: corefile-path
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /etc/kube-dns
      name: kube-dns-config
    - mountPath: /etc/coredns
      name: config-volume
    - mountPath: /etc/localtime
      name: localtime
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bjfmg
      readOnly: true
  dnsConfig:
    options:
    - name: timeout
      value: "2"
    - name: single-request-reopen
      value: ""
  dnsPolicy: Default
  enableServiceLinks: true
  hostNetwork: true
  nodeName: 192.168.0.73
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: node-local-dns
  serviceAccountName: node-local-dns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - emptyDir: {}
    name: corefile-path
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: xtables-lock
  - hostPath:
      path: /etc/localtime
      type: File
    name: localtime
  - configMap:
      defaultMode: 420
      name: kube-dns
      optional: true
    name: kube-dns-config
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile.base
      name: node-local-dns
    name: config-volume
  - name: kube-api-access-bjfmg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:09Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:03Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:02Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://2177e23a4f914c93ff8ddb0e1015891ce40efd5bf7774b38034a8ed5f7a7334b
    image: swr.tr-west-1.myhuaweicloud.com/hwofficial/k8s-dns-node-cache:1.23.1
    imageID: swr.tr-west-1.myhuaweicloud.com/hwofficial/k8s-dns-node-cache@sha256:aad3d23f778746562678efea1a454abd5925706fd7539ffc8a83434a012ee796
    lastState: {}
    name: node-cache
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-01T10:27:09Z"
    volumeMounts:
    - mountPath: /etc/corefile-path
      name: corefile-path
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /etc/kube-dns
      name: kube-dns-config
    - mountPath: /etc/coredns
      name: config-volume
    - mountPath: /etc/localtime
      name: localtime
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bjfmg
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.0.73
  hostIPs:
  - ip: 192.168.0.73
  phase: Running
  podIP: 192.168.0.73
  podIPs:
  - ip: 192.168.0.73
  qosClass: Burstable
  startTime: "2025-08-01T10:27:03Z"
