apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-08-01T08:45:39Z"
  generateName: node-local-dns-admission-controller-54868cc9d7-
  labels:
    k8s-app: node-local-dns-admission-controller
    pod-template-hash: 54868cc9d7
    release: cceaddon-node-local-dns
  name: node-local-dns-admission-controller-54868cc9d7-7726w
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: node-local-dns-admission-controller-54868cc9d7
    uid: 7a870017-6244-4739-9a83-8e0d61ebbc4e
  resourceVersion: "23806"
  uid: f19e773e-c896-4145-b6b2-62f8dc69c7a0
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/role
            operator: NotIn
            values:
            - virtual-kubelet
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - node-local-dns-admission-controller
          topologyKey: topology.kubernetes.io/zone
        weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: k8s-app
            operator: In
            values:
            - node-local-dns-admission-controller
        topologyKey: kubernetes.io/hostname
  containers:
  - command:
    - /bin/bash
    - -c
    - /var/paas/local-dns/local-dns-admission-controller --coredns-addr=10.247.3.10
      --localdns-addr=169.254.20.10 --cluster-domain=cluster.local --insecure-skip-tls-verify=true
    env:
    - name: PAAS_CRYPTO_PATH
      value: /srv/kubernetes
    image: swr.tr-west-1.myhuaweicloud.com/hwofficial/local-dns-admission-controller:1.6.66
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 9091
        scheme: HTTPS
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: webhook
    ports:
    - containerPort: 9090
      name: webhook
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 9091
        scheme: HTTPS
      initialDelaySeconds: 3
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 512Mi
    securityContext:
      runAsUser: 10000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /srv/kubernetes/root.key
      name: srvkube-root
    - mountPath: /srv/kubernetes/common_shared.key
      name: srvkube-common
    - mountPath: /admission.local.config/certificates
      name: admission-cert
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zdwqd
      readOnly: true
  dnsConfig:
    options:
    - name: single-request-reopen
      value: ""
    - name: timeout
      value: "2"
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 192.168.0.73
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 10000
  serviceAccount: node-local-dns
  serviceAccountName: node-local-dns
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 60
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 60
  volumes:
  - hostPath:
      path: /var/paas/srv/kubernetes/root.key
      type: ""
    name: srvkube-root
  - hostPath:
      path: /var/paas/srv/kubernetes/common_shared.key
      type: ""
    name: srvkube-common
  - name: admission-cert
    secret:
      defaultMode: 416
      secretName: node-local-dns-admission-secret
  - name: kube-api-access-zdwqd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:29Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:32Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:32Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://2b43197f932d755b4a2595d694daa88523f7d4f31d7373b09afae57f68b417fe
    image: swr.tr-west-1.myhuaweicloud.com/hwofficial/local-dns-admission-controller:1.6.66
    imageID: swr.tr-west-1.myhuaweicloud.com/hwofficial/local-dns-admission-controller@sha256:2267387d7fd8e6b8ec25d83df44e3081a9162f6e6128a92e133b41eec69a1efb
    lastState: {}
    name: webhook
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-01T10:27:28Z"
    volumeMounts:
    - mountPath: /srv/kubernetes/root.key
      name: srvkube-root
    - mountPath: /srv/kubernetes/common_shared.key
      name: srvkube-common
    - mountPath: /admission.local.config/certificates
      name: admission-cert
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-zdwqd
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.0.73
  hostIPs:
  - ip: 192.168.0.73
  phase: Running
  podIP: 10.0.1.5
  podIPs:
  - ip: 10.0.1.5
  qosClass: Guaranteed
  startTime: "2025-08-01T10:27:21Z"
