apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 82b999bfff05a83dd3dae4693921fbdf9bff3608ff68a2368f5029426ed0f681
  creationTimestamp: "2025-08-01T08:45:38Z"
  generateName: node-problem-controller-7c699f7f98-
  labels:
    app: node-problem-controller-cce
    pod-template-hash: 7c699f7f98
    release: cceaddon-npd
  name: node-problem-controller-7c699f7f98-lwzdt
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: node-problem-controller-7c699f7f98
    uid: 655885b0-f5aa-42aa-ae8c-0775941f0968
  resourceVersion: "23903"
  uid: 7c92a36f-9503-4c49-96e4-f62cb6808534
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - node-problem-controller-cce
          topologyKey: topology.kubernetes.io/zone
        weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - node-problem-controller-cce
        topologyKey: kubernetes.io/hostname
  containers:
  - command:
    - /bin/sh
    - -c
    - /var/paas/node-problem-controller/node-problem-controller --metrics-addr=$(POD_IP):9090
      --healthz-addr=$(POD_IP):8080
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: swr.tr-west-1.myhuaweicloud.com/hwofficial/node-problem-controller:1.19.20
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - sleep
          - "5"
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: npc
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 100m
        memory: 300Mi
      requests:
        cpu: 30m
        memory: 100Mi
    securityContext:
      readOnlyRootFilesystem: true
      runAsUser: 10000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: config-volume
    - mountPath: /etc/localtime
      name: localtime
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-76sfh
      readOnly: true
  dnsConfig:
    options:
    - name: single-request-reopen
      value: ""
    - name: timeout
      value: "2"
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 192.168.0.73
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 10000
    seccompProfile:
      type: Unconfined
  serviceAccount: cceaddon-npc
  serviceAccountName: cceaddon-npc
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node-problem-controller.cce.io
    operator: Exists
    tolerationSeconds: 60
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 60
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 60
  volumes:
  - configMap:
      defaultMode: 416
      name: cceaddon-npc-config
    name: config-volume
  - hostPath:
      path: /etc/localtime
      type: File
    name: localtime
  - name: kube-api-access-76sfh
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:30Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:42Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:42Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-01T10:27:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://3b01ed3fa42d94f6e2f7f58d103bc710d5a47179e9f8002549cc6e2639069806
    image: swr.tr-west-1.myhuaweicloud.com/hwofficial/node-problem-controller:1.19.20
    imageID: swr.tr-west-1.myhuaweicloud.com/hwofficial/node-problem-controller@sha256:93fa1b3fa38d3de605861a0be63c5d6adeb2998aabf75975fb2efe003c59f126
    lastState: {}
    name: npc
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-01T10:27:29Z"
    volumeMounts:
    - mountPath: /config
      name: config-volume
    - mountPath: /etc/localtime
      name: localtime
      readOnly: true
      recursiveReadOnly: Disabled
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-76sfh
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.0.73
  hostIPs:
  - ip: 192.168.0.73
  phase: Running
  podIP: 10.0.1.3
  podIPs:
  - ip: 10.0.1.3
  qosClass: Burstable
  startTime: "2025-08-01T10:27:21Z"
