apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: cceaddon-node-local-dns
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2025-08-01T08:45:38Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    release: cceaddon-node-local-dns
  name: local-dns-admission-controller
  namespace: kube-system
  resourceVersion: "666"
  uid: 6bdb05ce-8533-4c87-9748-09a74eec8b9b
spec:
  clusterIP: 10.247.112.173
  clusterIPs:
  - 10.247.112.173
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: node-local-dns-admission-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
